// Generated by scripts/togoid-patterns.ts on 2026-09-20 from TogoID's dataset.yaml
// (https://raw.githubusercontent.com/togoid/togoid-config/refs/heads/main/config/dataset.yaml), which curates the ID syntax of each database. Used to guess the namespace of an input written without
// one (spec-service §6). Regenerate when TogoID adds or changes a pattern.
export interface TogoidPattern {
  /** TogoCoord namespace the dataset's IDs belong to. */
  namespace: string;
  /** TogoID dataset name. */
  dataset: string;
  pattern: RegExp;
}

export const TOGOID_PATTERNS: readonly TogoidPattern[] = [
  { namespace: "refseq", dataset: "refseq_protein", pattern: /^(?<id>[ANXYWZ]P_\d+)(?:\.\d+)?$/ },
  { namespace: "refseq", dataset: "refseq_rna", pattern: /^(?<id>(?:NM|NR|XM|XR)_\d+)(?:\.\d+)?$/ },
  { namespace: "refseq", dataset: "refseq_genomic", pattern: /^(?<id>(?:AC_|N[CGTW]_|NZ_[A-Z]+)\d+)(?:\.\d+)?$/ },
  { namespace: "ensembl", dataset: "ensembl_protein", pattern: /^(?:(?:(?<id1>ENS[A-Z]*P\d{11})(?:\.\d+)?)|(?<id2>FBpp\d{7})|(?:(?<id3>MGP_[A-Za-z0-9]+_P\d{7})(?:\.\d+)?)|(?<id4>LRG_\d+p\d+(?:-\d)?)|(?<id5>(?:[A-Za-z0-9][A-Za-z0-9_]+)\.t?\d+[a-z]?(?:\.\d+)?)|(?<id6>Y[A-Z]{2}\d{3}[A-Z](?:-[A-Z])?)|(?<id7>Q\d{4}))$/ },
  { namespace: "ensembl", dataset: "ensembl_transcript", pattern: /^(?:(?:(?<id1>ENS[A-Z]*T\d{11})(?:\.\d+)?)|(?<id2>FBtr\d{7})|(?:(?<id3>MGP_[A-Za-z0-9]+_T\d{7})(?:\.\d+)?)|(?<id4>LRG_\d+t\d+(?:-\d)?)|(?<id5>(?:[A-Za-z0-9][A-Za-z0-9_]+)\.t?\d+[a-z]?(?:\.\d+)?)|(?<id6>Y[A-Z]{2}\d{3}[A-Z](?:-[A-Z])?(?:_[a-z]{1,3}RNA)?)|(?<id7>Q\d{4}_[a-z]{1,3}RNA)|(?<id8>[A-Z]{3}\d{1,3}(?:-\d)?_[a-z]{1,3}RNA)|(?<id9>snR\d+-?[A-Za-z]?_sno?RNA)|(?<id10>t[A-Z]\(?:[ACGUX]{3}\)[A-Z]\d?_tRNA))$/ },
  { namespace: "ensembl", dataset: "ensembl_gene", pattern: /^(?:(?:(?<id1>ENS[A-Z]*G\d{11})(?:\.\d+)?)|(?<id2>FBgn\d{7})|(?:(?<id3>MGP_[A-Za-z0-9]+_G\d{7})(?:\.\d+)?)|(?<id4>LRG_\d+)|(?<id5>WBGene\d{8})|(?<id6>Y[A-Z]{2}\d{3}[A-Z](?:-[A-Z])?)|(?<id7>Q\d{4})|(?<id8>[A-Z]{3}\d{1,3}(?:-\d)?)|(?<id9>snR\d+-?[A-Za-z]?)|(?<id10>t[A-Z]\(?:[ACGUX]{3}\)[A-Z]\d?))$/ },
  { namespace: "uniprot", dataset: "uniprot", pattern: /^(?:(?<id1>[A-NR-Z][0-9](?:[A-Z][A-Z0-9][A-Z0-9][0-9]){1,2}(?:-\d+)?)|(?<id2>[OPQ][0-9][A-Z0-9][A-Z0-9][A-Z0-9][0-9](?:-\d+)?)(?:\.\d+)?)$/ },
  { namespace: "uniprot", dataset: "uniprot_isoform", pattern: /^(?:(?<id1>[A-NR-Z][0-9](?:[A-Z][A-Z0-9][A-Z0-9][0-9]){1,2}(?:-\d+))|(?<id2>[OPQ][0-9][A-Z0-9][A-Z0-9][A-Z0-9][0-9](?:-\d+)))$/ },
  { namespace: "insdc", dataset: "insdc", pattern: /^(?:insdc:)?(?<id>[A-Z]\d{5}|[A-Z]{2}\d{6}|[A-Z]{4}\d{8}|[A-J][A-Z]{2}\d{5}|[A-Z]{4,}\d{9})(?:\.\d+)?$/ },
  { namespace: "insdc", dataset: "insdc_cds", pattern: /^(?:insdc.cds:)?(?<id>([A-Z]\d{5}|[A-Z]{2}\d{6}|[A-Z]{3}\d{5}|[A-Z]{4}\d{8}|[A-J][A-Z]{2}\d{5}))(?:\.\d+)?$/ },
  { namespace: "pdb", dataset: "pdb", pattern: /^(?<id>[0-9][A-Za-z0-9]{3})$/ },
];
