// Generated from NCBI gc.prt (https://ftp.ncbi.nih.gov/entrez/misc/data/gc.prt, retrieved 2026-09-18).
// Codon index = 16*b1 + 4*b2 + b3 with T=0, C=1, A=2, G=3.
export const GENETIC_CODES: Readonly<Record<number, { aa: string; starts: string }>> = {
  1: { aa: "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "---M------**--*----M---------------M----------------------------" },
  2: { aa: "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSS**VVVVAAAADDEEGGGG", starts: "----------**--------------------MMMM----------**---M------------" },
  3: { aa: "FFLLSSSSYY**CCWWTTTTPPPPHHQQRRRRIIMMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "----------**----------------------MM---------------M------------" },
  4: { aa: "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "--MM------**-------M------------MMMM---------------M------------" },
  5: { aa: "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSSSVVVVAAAADDEEGGGG", starts: "---M------**--------------------MMMM---------------M------------" },
  6: { aa: "FFLLSSSSYYQQCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "--------------*--------------------M----------------------------" },
  9: { aa: "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNNKSSSSVVVVAAAADDEEGGGG", starts: "----------**-----------------------M---------------M------------" },
  10: { aa: "FFLLSSSSYY**CCCWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "----------**-----------------------M----------------------------" },
  11: { aa: "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "---M------**--*----M------------MMMM---------------M------------" },
  12: { aa: "FFLLSSSSYY**CC*WLLLSPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "----------**--*----M---------------M----------------------------" },
  13: { aa: "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNKKSSGGVVVVAAAADDEEGGGG", starts: "---M------**----------------------MM---------------M------------" },
  14: { aa: "FFLLSSSSYYY*CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNNKSSSSVVVVAAAADDEEGGGG", starts: "-----------*-----------------------M----------------------------" },
  15: { aa: "FFLLSSSSYY*QCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "----------*---*--------------------M----------------------------" },
  16: { aa: "FFLLSSSSYY*LCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "----------*---*--------------------M----------------------------" },
  21: { aa: "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIMMTTTTNNNKSSSSVVVVAAAADDEEGGGG", starts: "----------**-----------------------M---------------M------------" },
  22: { aa: "FFLLSS*SYY*LCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "------*---*---*--------------------M----------------------------" },
  23: { aa: "FF*LSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "--*-------**--*-----------------M--M---------------M------------" },
  24: { aa: "FFLLSSSSYY**CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSSKVVVVAAAADDEEGGGG", starts: "---M------**-------M---------------M---------------M------------" },
  25: { aa: "FFLLSSSSYY**CCGWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "---M------**-----------------------M---------------M------------" },
  26: { aa: "FFLLSSSSYY**CC*WLLLAPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "----------**--*----M---------------M----------------------------" },
  27: { aa: "FFLLSSSSYYQQCCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "--------------*--------------------M----------------------------" },
  28: { aa: "FFLLSSSSYYQQCCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "----------**--*--------------------M----------------------------" },
  29: { aa: "FFLLSSSSYYYYCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "--------------*--------------------M----------------------------" },
  30: { aa: "FFLLSSSSYYEECC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "--------------*--------------------M----------------------------" },
  31: { aa: "FFLLSSSSYYEECCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "----------**-----------------------M----------------------------" },
  32: { aa: "FFLLSSSSYY*WCC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG", starts: "---M------*---*----M------------MMMM---------------M------------" },
  33: { aa: "FFLLSSSSYYY*CCWWLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSSKVVVVAAAADDEEGGGG", starts: "---M-------*-------M---------------M---------------M------------" },
};
