// Regenerate service/src/togoid-patterns.ts from TogoID's dataset.yaml (DBCLS), which curates the ID syntax of each
// database. TogoCoord uses those patterns to guess the namespace of an input written without one (docs/spec-service.md
// §6): `NP_000572.2:49` is read as `refseq:NP_000572.2:49`.
//   node scripts/togoid-patterns.ts [> service/src/togoid-patterns.ts]
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE = "https://raw.githubusercontent.com/togoid/togoid-config/refs/heads/main/config/dataset.yaml";
/** TogoID datasets whose IDs are sequences TogoCoord addresses, by the namespace they belong to. */
const DATASETS: Record<string, string[]> = {
  refseq: ["refseq_protein", "refseq_rna", "refseq_genomic"],
  ensembl: ["ensembl_protein", "ensembl_transcript", "ensembl_gene"],
  uniprot: ["uniprot", "uniprot_isoform"],
  insdc: ["insdc", "insdc_cds"],
  pdb: ["pdb"],
};

const yaml = await (await fetch(SOURCE)).text();
const regexes = new Map<string, string>();
let dataset: string | undefined;
for (const line of yaml.split("\n")) {
  const name = /^([a-z0-9_]+):\s*$/.exec(line);
  if (name) {
    dataset = name[1];
    continue;
  }
  const regex = /^\s{2}regex:\s*['"](.*)['"]\s*$/.exec(line);
  if (regex && dataset) regexes.set(dataset, regex[1]!);
}

const entries: string[] = [];
for (const [namespace, names] of Object.entries(DATASETS)) {
  for (const name of names) {
    const pattern = regexes.get(name);
    if (!pattern) throw new Error(`${name}: no regex in ${SOURCE}`);
    new RegExp(pattern); // fails here rather than at runtime
    entries.push(`  { namespace: "${namespace}", dataset: "${name}", pattern: /${pattern.replace(/\//g, "\\/")}/ },`);
  }
}

const out = `// Generated by scripts/togoid-patterns.ts on ${new Date().toISOString().slice(0, 10)} from TogoID's dataset.yaml
// (${SOURCE}), which curates the ID syntax of each database. Used to guess the namespace of an input written without
// one (spec-service §6). Regenerate when TogoID adds or changes a pattern.
export interface TogoidPattern {
  /** TogoCoord namespace the dataset's IDs belong to. */
  namespace: string;
  /** TogoID dataset name. */
  dataset: string;
  pattern: RegExp;
}

export const TOGOID_PATTERNS: readonly TogoidPattern[] = [
${entries.join("\n")}
];
`;
writeFileSync(join(new URL("..", import.meta.url).pathname, "service/src/togoid-patterns.ts"), out);
process.stderr.write(`service/src/togoid-patterns.ts: ${entries.length} patterns from ${regexes.size} TogoID datasets\n`);
