// Guessing the database of an accession written without one (spec-service §6). The patterns come from TogoID
// (service/src/togoid-patterns.ts, regenerated by scripts/togoid-patterns.ts), so these cases also guard that table.
import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { NamespaceRegistry } from "@togocoord/core";
import { guessNamespaces, inferNamespace } from "../src/infer.ts";

describe("inferring the database of a bare accession (spec-service §6)", () => {
  const registry = new NamespaceRegistry();
  const infer = (accession: string, loaded: string[] = []) => inferNamespace(accession, registry, (r) => loaded.includes(r));

  it("reads an accession whose syntax belongs to one database", () => {
    const cases: Record<string, string> = {
      "NP_000572.2": "refseq:NP_000572.2",
      "NM_000546.6": "refseq:NM_000546.6",
      "NC_000007.14": "refseq:NC_000007.14",
      "ENSP00000269305": "ensembl:ENSP00000269305",
      "ENST00000269305.9": "ensembl:ENST00000269305.9",
      "ENSG00000141510": "ensembl:ENSG00000141510",
      "ENSMUSP00000020717": "ensembl:ENSMUSP00000020717",
      "Q9SZP7": "uniprot:Q9SZP7",
      "P07203-2": "uniprot:P07203-2",
      "BX897699.1": "insdc:BX897699.1",
      "UPI0000000001": "uniparc:UPI0000000001",
      "4hhb.A": "pdb:4HHB.A", // TogoID knows the entry 4HHB; we address one of its chains
    };
    for (const [accession, ref] of Object.entries(cases)) assert.equal(infer(accession).ref, ref, accession);
  });

  it("prefers a database we hold when one ID form belongs to two", () => {
    // P07203 is a UniProt accession and an INSDC one ([A-Z] + 5 digits) at the same time.
    assert.deepEqual(infer("P07203").ambiguous, ["insdc:P07203", "uniprot:P07203"]);
    assert.equal(infer("P07203", ["uniprot:P07203"]).ref, "uniprot:P07203");
    assert.equal(infer("P07203", ["insdc:P07203"]).ref, "insdc:P07203");
    assert.deepEqual(infer("P07203", ["insdc:P07203", "uniprot:P07203"]).ambiguous, ["insdc:P07203", "uniprot:P07203"]);
  });

  it("gives nothing for what no database's syntax matches", () => {
    for (const text of ["TP53", "4HHB", "chr7", "hg38", ""]) assert.deepEqual(infer(text), {}, text);
  });

  it("does not let TogoID's generic Ensembl patterns claim other databases' accessions", () => {
    // ensembl_transcript accepts <name>.<number>, which every versioned accession matches; ours must not become that.
    for (const accession of ["NM_000546.6", "BX897699.1", "AC_000001.1"]) {
      assert.deepEqual(guessNamespaces(accession, registry, () => false).map((g) => g.namespace), [accession.includes("_") ? "refseq" : "insdc"], accession);
    }
  });
});
